export default {
  plant1: {
    image1b: "/assets/images/plantb/PlantB1A.png",
    image2b: "/assets/images/plantb/PlantB1B.png",
    image1: "/assets/images/plant/Plant00.gif",
    image2: "/assets/images/plant/Plant1A.gif",
    image3: "/assets/images/plant/Plant1B.gif",
    point: 50,
  },
  plant2: {
    image1b: "/assets/images/plantb/PlantB2A.png",
    image2b: "/assets/images/plantb/PlantB2B.png",
    image1: "/assets/images/plant/Plant00.gif",
    image2: "/assets/images/plant/Plant2A.gif",
    image3: "/assets/images/plant/Plant2B.gif",
    point: 100,
  },
  plant3: {
    image1b: "/assets/images/plantb/PlantB3A.png",
    image2b: "/assets/images/plantb/PlantB3B.png",
    image1: "/assets/images/plant/Plant00.gif",
    image2: "/assets/images/plant/Plant3A.gif",
    image3: "/assets/images/plant/Plant3B.gif",
    point: 150,
  },
  plant4: {
    image1b: "/assets/images/plantb/PlantB4A.png",
    image2b: "/assets/images/plantb/PlantB4B.png",
    image1: "/assets/images/plant/Plant00.gif",
    image2: "/assets/images/plant/Plant4A.gif",
    image3: "/assets/images/plant/Plant4B.gif",
    point: 50,
  },
  plant5: {
    image1b: "/assets/images/plantb/PlantB5A.png",
    image2b: "/assets/images/plantb/PlantB5B.png",
    image1: "/assets/images/plant/Plant00.gif",
    image2: "/assets/images/plant/Plant5A.gif",
    image3: "/assets/images/plant/Plant5B.gif",
    point: 175,
  },
  plant6: {
    image1b: "/assets/images/plantb/PlantB6A.png",
    image2b: "/assets/images/plantb/PlantB6B.png",
    image1: "/assets/images/plant/Plant00.gif",
    image2: "/assets/images/plant/Plant6A.gif",
    image3: "/assets/images/plant/Plant6B.gif",
    point: 50,
  },
  plant7: {
    image1b: "/assets/images/plantb/PlantB7A.png",
    image2b: "/assets/images/plantb/PlantB7B.png",
    image1: "/assets/images/plant/Plant00.gif",
    image2: "/assets/images/plant/Plant7A.gif",
    image3: "/assets/images/plant/Plant7B.gif",
    point: 200,
  },
};
