export default {
  plant1: {
    timer: 40,
    overTimer: 5,
    salePrice: 70,
    purchasePrice: 50,
    image0: "./assets/images/plant/Seed.png",
    image1: "./assets/images/plant/Plant1A.gif",
    image2: "./assets/images/plant/Plant1B.gif",
    image1b: "./assets/images/plantb/PlantB1A.png",
    image2b: "./assets/images/plantb/PlantB1B.png",
  },
  plant2: {
    timer: 50,
    overTimer: 5,
    salePrice: 140,
    purchasePrice: 100,
    image0: "./assets/images/plant/Seed.png",
    image1: "./assets/images/plant/Plant2A.gif",
    image2: "./assets/images/plant/Plant2B.gif",
    image1b: "./assets/images/plantb/PlantB2A.png",
    image2b: "./assets/images/plantb/PlantB2B.png",
  },
  plant3: {
    timer: 60,
    overTimer: 5,
    salePrice: 210,
    purchasePrice: 150,
    image0: "./assets/images/plant/Seed.png",
    image1: "./assets/images/plant/Plant3A.gif",
    image2: "./assets/images/plant/Plant3B.gif",
    image1b: "./assets/images/plantb/PlantB3A.png",
    image2b: "./assets/images/plantb/PlantB3B.png",
  },
  plant4: {
    timer: 40,
    overTimer: 5,
    salePrice: 70,
    purchasePrice: 50,
    image0: "./assets/images/plant/Seed.png",
    image1: "./assets/images/plant/Plant4A.gif",
    image2: "./assets/images/plant/Plant4B.gif",
    image1b: "./assets/images/plantb/PlantB4A.png",
    image2b: "./assets/images/plantb/PlantB4B.png",
  },
  plant5: {
    timer: 70,
    overTimer: 5,
    salePrice: 245,
    purchasePrice: 175,
    image0: "./assets/images/plant/Seed.png",
    image1: "./assets/images/plant/Plant5A.gif",
    image2: "./assets/images/plant/Plant5B.gif",
    image1b: "./assets/images/plantb/PlantB5A.png",
    image2b: "./assets/images/plantb/PlantB5B.png",
  },
  plant6: {
    timer: 40,
    overTimer: 5,
    salePrice: 70,
    purchasePrice: 50,
    image0: "./assets/images/plant/Seed.png",
    image1: "./assets/images/plant/Plant6A.gif",
    image2: "./assets/images/plant/Plant6B.gif",
    image1b: "./assets/images/plantb/PlantB6A.png",
    image2b: "./assets/images/plantb/PlantB6B.png",
  },
  plant7: {
    timer: 80,
    overTimer: 5,
    salePrice: 280,
    purchasePrice: 200,
    image0: "./assets/images/plant/Seed.png",
    image1: "./assets/images/plant/Plant7A.gif",
    image2: "./assets/images/plant/Plant7B.gif",
    image1b: "./assets/images/plantb/PlantB7A.png",
    image2b: "./assets/images/plantb/PlantB7B.png",
  },
};
